// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slave.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeregisterNotifyRequest struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeregisterNotifyRequest) Reset()         { *m = DeregisterNotifyRequest{} }
func (m *DeregisterNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*DeregisterNotifyRequest) ProtoMessage()    {}
func (*DeregisterNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{0}
}

func (m *DeregisterNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeregisterNotifyRequest.Unmarshal(m, b)
}
func (m *DeregisterNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeregisterNotifyRequest.Marshal(b, m, deterministic)
}
func (m *DeregisterNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeregisterNotifyRequest.Merge(m, src)
}
func (m *DeregisterNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_DeregisterNotifyRequest.Size(m)
}
func (m *DeregisterNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeregisterNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeregisterNotifyRequest proto.InternalMessageInfo

func (m *DeregisterNotifyRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type NoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoResponse) Reset()         { *m = NoResponse{} }
func (m *NoResponse) String() string { return proto.CompactTextString(m) }
func (*NoResponse) ProtoMessage()    {}
func (*NoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{1}
}

func (m *NoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoResponse.Unmarshal(m, b)
}
func (m *NoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoResponse.Marshal(b, m, deterministic)
}
func (m *NoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoResponse.Merge(m, src)
}
func (m *NoResponse) XXX_Size() int {
	return xxx_messageInfo_NoResponse.Size(m)
}
func (m *NoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NoResponse proto.InternalMessageInfo

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{4}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{5}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type DelRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{6}
}

func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (m *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(m, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResponse) Reset()         { *m = DelResponse{} }
func (m *DelResponse) String() string { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()    {}
func (*DelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{7}
}

func (m *DelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResponse.Unmarshal(m, b)
}
func (m *DelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResponse.Marshal(b, m, deterministic)
}
func (m *DelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResponse.Merge(m, src)
}
func (m *DelResponse) XXX_Size() int {
	return xxx_messageInfo_DelResponse.Size(m)
}
func (m *DelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelResponse proto.InternalMessageInfo

func (m *DelResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type MoveDataRequest struct {
	FromLabel            int32    `protobuf:"varint,1,opt,name=from_label,json=fromLabel,proto3" json:"from_label,omitempty"`
	ToLabel              int32    `protobuf:"varint,2,opt,name=to_label,json=toLabel,proto3" json:"to_label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDataRequest) Reset()         { *m = MoveDataRequest{} }
func (m *MoveDataRequest) String() string { return proto.CompactTextString(m) }
func (*MoveDataRequest) ProtoMessage()    {}
func (*MoveDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{8}
}

func (m *MoveDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDataRequest.Unmarshal(m, b)
}
func (m *MoveDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDataRequest.Marshal(b, m, deterministic)
}
func (m *MoveDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDataRequest.Merge(m, src)
}
func (m *MoveDataRequest) XXX_Size() int {
	return xxx_messageInfo_MoveDataRequest.Size(m)
}
func (m *MoveDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDataRequest proto.InternalMessageInfo

func (m *MoveDataRequest) GetFromLabel() int32 {
	if m != nil {
		return m.FromLabel
	}
	return 0
}

func (m *MoveDataRequest) GetToLabel() int32 {
	if m != nil {
		return m.ToLabel
	}
	return 0
}

type MoveDataResponse struct {
	Kvs                  []*MoveDataResponse_Kv `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MoveDataResponse) Reset()         { *m = MoveDataResponse{} }
func (m *MoveDataResponse) String() string { return proto.CompactTextString(m) }
func (*MoveDataResponse) ProtoMessage()    {}
func (*MoveDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{9}
}

func (m *MoveDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDataResponse.Unmarshal(m, b)
}
func (m *MoveDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDataResponse.Marshal(b, m, deterministic)
}
func (m *MoveDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDataResponse.Merge(m, src)
}
func (m *MoveDataResponse) XXX_Size() int {
	return xxx_messageInfo_MoveDataResponse.Size(m)
}
func (m *MoveDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDataResponse proto.InternalMessageInfo

func (m *MoveDataResponse) GetKvs() []*MoveDataResponse_Kv {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type MoveDataResponse_Kv struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDataResponse_Kv) Reset()         { *m = MoveDataResponse_Kv{} }
func (m *MoveDataResponse_Kv) String() string { return proto.CompactTextString(m) }
func (*MoveDataResponse_Kv) ProtoMessage()    {}
func (*MoveDataResponse_Kv) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{9, 0}
}

func (m *MoveDataResponse_Kv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDataResponse_Kv.Unmarshal(m, b)
}
func (m *MoveDataResponse_Kv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDataResponse_Kv.Marshal(b, m, deterministic)
}
func (m *MoveDataResponse_Kv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDataResponse_Kv.Merge(m, src)
}
func (m *MoveDataResponse_Kv) XXX_Size() int {
	return xxx_messageInfo_MoveDataResponse_Kv.Size(m)
}
func (m *MoveDataResponse_Kv) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDataResponse_Kv.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDataResponse_Kv proto.InternalMessageInfo

func (m *MoveDataResponse_Kv) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MoveDataResponse_Kv) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{10}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetAllResponse struct {
	Kvs                  []*GetAllResponse_Kvs `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{11}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetKvs() []*GetAllResponse_Kvs {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type GetAllResponse_Kvs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse_Kvs) Reset()         { *m = GetAllResponse_Kvs{} }
func (m *GetAllResponse_Kvs) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse_Kvs) ProtoMessage()    {}
func (*GetAllResponse_Kvs) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{11, 0}
}

func (m *GetAllResponse_Kvs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse_Kvs.Unmarshal(m, b)
}
func (m *GetAllResponse_Kvs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse_Kvs.Marshal(b, m, deterministic)
}
func (m *GetAllResponse_Kvs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse_Kvs.Merge(m, src)
}
func (m *GetAllResponse_Kvs) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse_Kvs.Size(m)
}
func (m *GetAllResponse_Kvs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse_Kvs.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse_Kvs proto.InternalMessageInfo

func (m *GetAllResponse_Kvs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetAllResponse_Kvs) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DeregisterNotifyRequest)(nil), "DeregisterNotifyRequest")
	proto.RegisterType((*NoResponse)(nil), "NoResponse")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*PutRequest)(nil), "PutRequest")
	proto.RegisterType((*PutResponse)(nil), "PutResponse")
	proto.RegisterType((*DelRequest)(nil), "DelRequest")
	proto.RegisterType((*DelResponse)(nil), "DelResponse")
	proto.RegisterType((*MoveDataRequest)(nil), "MoveDataRequest")
	proto.RegisterType((*MoveDataResponse)(nil), "MoveDataResponse")
	proto.RegisterType((*MoveDataResponse_Kv)(nil), "MoveDataResponse.Kv")
	proto.RegisterType((*GetAllRequest)(nil), "GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "GetAllResponse")
	proto.RegisterType((*GetAllResponse_Kvs)(nil), "GetAllResponse.Kvs")
}

func init() { proto.RegisterFile("slave.proto", fileDescriptor_5203a3ed916706d4) }

var fileDescriptor_5203a3ed916706d4 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0xae, 0xeb, 0x8e, 0x4b, 0x5b, 0xcc, 0x24, 0x42, 0x24, 0xa0, 0x8a, 0x04, 0x1b,
	0x12, 0x33, 0x52, 0xc7, 0x0b, 0xe2, 0x89, 0xa9, 0x52, 0x1f, 0x02, 0xd3, 0x14, 0xde, 0x78, 0x41,
	0x29, 0xb9, 0x85, 0xa9, 0x61, 0x2e, 0x89, 0x6b, 0xa9, 0xbf, 0xc0, 0x97, 0xf1, 0x59, 0xc8, 0x6e,
	0xa2, 0x64, 0xd9, 0x22, 0xed, 0xcd, 0xbe, 0xe7, 0xf8, 0x9c, 0xa3, 0xeb, 0x7b, 0xc1, 0x8a, 0x2c,
	0xd1, 0x24, 0x36, 0xb9, 0x54, 0x32, 0x3c, 0xc3, 0xd3, 0x39, 0xe5, 0xf4, 0xf3, 0xba, 0x50, 0x94,
	0x5f, 0x4a, 0x75, 0xbd, 0xda, 0xc5, 0xf4, 0x67, 0x4b, 0x85, 0xe2, 0x1c, 0xbd, 0x24, 0x4d, 0x73,
	0xdf, 0x99, 0x3a, 0xa7, 0x47, 0xb1, 0x3d, 0x87, 0x43, 0xe0, 0x52, 0xc6, 0x54, 0x6c, 0xe4, 0x4d,
	0x41, 0xe1, 0x0b, 0x60, 0x41, 0xaa, 0xe2, 0x4f, 0xe0, 0xad, 0x69, 0x57, 0xd2, 0xcd, 0x31, 0x3c,
	0x07, 0xb3, 0xf8, 0x9e, 0xce, 0x47, 0x70, 0xe5, 0xda, 0xe2, 0x83, 0xd8, 0x95, 0x6b, 0x7e, 0x8c,
	0x03, 0x9d, 0x64, 0x5b, 0xf2, 0x5d, 0xfb, 0x64, 0x7f, 0x09, 0xdf, 0x03, 0x57, 0xdb, 0x6e, 0xd1,
	0x8e, 0x57, 0x27, 0x60, 0xf6, 0x55, 0x69, 0xe5, 0xe3, 0xf0, 0x47, 0x4e, 0x89, 0xa2, 0xb4, 0xf4,
	0xab, 0xae, 0x26, 0xf3, 0x9c, 0xb2, 0xee, 0xcc, 0x27, 0x60, 0x16, 0xaf, 0x85, 0x52, 0xca, 0xa8,
	0x21, 0x54, 0x5e, 0xc3, 0x08, 0xe3, 0x2f, 0x52, 0xd3, 0x3c, 0x51, 0x49, 0xa5, 0xf6, 0x1c, 0x58,
	0xe5, 0xf2, 0xf7, 0xf7, 0x2c, 0x59, 0x52, 0x66, 0xf9, 0x07, 0xf1, 0x91, 0xa9, 0x7c, 0x36, 0x05,
	0xfe, 0x0c, 0x03, 0x25, 0x4b, 0xd0, 0xb5, 0xe0, 0xa1, 0x92, 0x16, 0x0a, 0x7f, 0x61, 0x52, 0x8b,
	0x95, 0xd6, 0xaf, 0xe1, 0xad, 0x75, 0xe1, 0x3b, 0x53, 0xef, 0x94, 0xcd, 0x8e, 0x45, 0x1b, 0x17,
	0x91, 0x8e, 0x0d, 0x21, 0x78, 0x0b, 0x37, 0xd2, 0x0f, 0x6e, 0xd4, 0x18, 0x8f, 0x16, 0xa4, 0x3e,
	0x65, 0x55, 0x0b, 0xc2, 0x15, 0x46, 0x55, 0xa1, 0x34, 0x7e, 0xd5, 0x34, 0x7e, 0x22, 0x6e, 0xa3,
	0x22, 0xd2, 0xc5, 0xde, 0xf7, 0x0c, 0x5e, 0xa4, 0x8b, 0x87, 0x1a, 0xcf, 0xfe, 0x39, 0xe8, 0x99,
	0xfc, 0x7c, 0x0a, 0x6f, 0x41, 0x8a, 0x33, 0x51, 0xcf, 0x4e, 0x30, 0x14, 0xcd, 0x41, 0x79, 0x83,
	0xfe, 0xde, 0x94, 0x8f, 0xc4, 0xad, 0xb0, 0xc1, 0xb8, 0x95, 0xc6, 0x88, 0x5d, 0x6d, 0x8d, 0x58,
	0x3d, 0x33, 0xc1, 0x50, 0x34, 0x47, 0x61, 0x0a, 0x6f, 0x4e, 0x19, 0x67, 0xa2, 0xfe, 0xf6, 0x60,
	0x28, 0x9a, 0x7f, 0xfc, 0x0e, 0x83, 0xaa, 0xb9, 0x7c, 0x22, 0x5a, 0x9f, 0x1a, 0x3c, 0xbe, 0xd3,
	0xf9, 0xd9, 0x5f, 0x07, 0xcc, 0x14, 0xbe, 0xaa, 0xe4, 0x26, 0xbd, 0xd8, 0xf1, 0x0f, 0x98, 0xb4,
	0x97, 0x88, 0xfb, 0xa2, 0x63, 0xaf, 0x02, 0x26, 0xea, 0x15, 0xe2, 0x2f, 0xef, 0xc9, 0xdf, 0x26,
	0xdc, 0x89, 0xdf, 0x24, 0x5c, 0xf4, 0xbf, 0xf5, 0xc4, 0xc7, 0xcd, 0x72, 0xd9, 0xb7, 0x0b, 0x7d,
	0xfe, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x47, 0xcb, 0x64, 0xbc, 0xdf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	MoveData(ctx context.Context, in *MoveDataRequest, opts ...grpc.CallOption) (*MoveDataResponse, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Data/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/Data/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/Data/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, "/Data/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) MoveData(ctx context.Context, in *MoveDataRequest, opts ...grpc.CallOption) (*MoveDataResponse, error) {
	out := new(MoveDataResponse)
	err := c.cc.Invoke(ctx, "/Data/MoveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Del(context.Context, *DelRequest) (*DelResponse, error)
	MoveData(context.Context, *MoveDataRequest) (*MoveDataResponse, error)
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_MoveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).MoveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Data/MoveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).MoveData(ctx, req.(*MoveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Data_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Data_GetAll_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Data_Put_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Data_Del_Handler,
		},
		{
			MethodName: "MoveData",
			Handler:    _Data_MoveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slave.proto",
}

// DataStandByClient is the client API for DataStandBy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataStandByClient interface {
	DeregisterNotify(ctx context.Context, in *DeregisterNotifyRequest, opts ...grpc.CallOption) (*NoResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*NoResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*NoResponse, error)
}

type dataStandByClient struct {
	cc *grpc.ClientConn
}

func NewDataStandByClient(cc *grpc.ClientConn) DataStandByClient {
	return &dataStandByClient{cc}
}

func (c *dataStandByClient) DeregisterNotify(ctx context.Context, in *DeregisterNotifyRequest, opts ...grpc.CallOption) (*NoResponse, error) {
	out := new(NoResponse)
	err := c.cc.Invoke(ctx, "/DataStandBy/DeregisterNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStandByClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*NoResponse, error) {
	out := new(NoResponse)
	err := c.cc.Invoke(ctx, "/DataStandBy/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStandByClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*NoResponse, error) {
	out := new(NoResponse)
	err := c.cc.Invoke(ctx, "/DataStandBy/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataStandByServer is the server API for DataStandBy service.
type DataStandByServer interface {
	DeregisterNotify(context.Context, *DeregisterNotifyRequest) (*NoResponse, error)
	Put(context.Context, *PutRequest) (*NoResponse, error)
	Del(context.Context, *DelRequest) (*NoResponse, error)
}

func RegisterDataStandByServer(s *grpc.Server, srv DataStandByServer) {
	s.RegisterService(&_DataStandBy_serviceDesc, srv)
}

func _DataStandBy_DeregisterNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStandByServer).DeregisterNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataStandBy/DeregisterNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStandByServer).DeregisterNotify(ctx, req.(*DeregisterNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStandBy_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStandByServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataStandBy/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStandByServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStandBy_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStandByServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataStandBy/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStandByServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataStandBy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataStandBy",
	HandlerType: (*DataStandByServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeregisterNotify",
			Handler:    _DataStandBy_DeregisterNotify_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _DataStandBy_Put_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _DataStandBy_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slave.proto",
}
