// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slave.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{2}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{3}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type DelRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{4}
}

func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (m *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(m, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResponse) Reset()         { *m = DelResponse{} }
func (m *DelResponse) String() string { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()    {}
func (*DelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{5}
}

func (m *DelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResponse.Unmarshal(m, b)
}
func (m *DelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResponse.Marshal(b, m, deterministic)
}
func (m *DelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResponse.Merge(m, src)
}
func (m *DelResponse) XXX_Size() int {
	return xxx_messageInfo_DelResponse.Size(m)
}
func (m *DelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelResponse proto.InternalMessageInfo

func (m *DelResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type MoveDataRequest struct {
	FromLabel            int32    `protobuf:"varint,1,opt,name=from_label,json=fromLabel,proto3" json:"from_label,omitempty"`
	ToLabel              int32    `protobuf:"varint,2,opt,name=to_label,json=toLabel,proto3" json:"to_label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDataRequest) Reset()         { *m = MoveDataRequest{} }
func (m *MoveDataRequest) String() string { return proto.CompactTextString(m) }
func (*MoveDataRequest) ProtoMessage()    {}
func (*MoveDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{6}
}

func (m *MoveDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDataRequest.Unmarshal(m, b)
}
func (m *MoveDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDataRequest.Marshal(b, m, deterministic)
}
func (m *MoveDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDataRequest.Merge(m, src)
}
func (m *MoveDataRequest) XXX_Size() int {
	return xxx_messageInfo_MoveDataRequest.Size(m)
}
func (m *MoveDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDataRequest proto.InternalMessageInfo

func (m *MoveDataRequest) GetFromLabel() int32 {
	if m != nil {
		return m.FromLabel
	}
	return 0
}

func (m *MoveDataRequest) GetToLabel() int32 {
	if m != nil {
		return m.ToLabel
	}
	return 0
}

type MoveDataResponse struct {
	Kvs                  []*MoveDataResponse_Kv `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MoveDataResponse) Reset()         { *m = MoveDataResponse{} }
func (m *MoveDataResponse) String() string { return proto.CompactTextString(m) }
func (*MoveDataResponse) ProtoMessage()    {}
func (*MoveDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{7}
}

func (m *MoveDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDataResponse.Unmarshal(m, b)
}
func (m *MoveDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDataResponse.Marshal(b, m, deterministic)
}
func (m *MoveDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDataResponse.Merge(m, src)
}
func (m *MoveDataResponse) XXX_Size() int {
	return xxx_messageInfo_MoveDataResponse.Size(m)
}
func (m *MoveDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDataResponse proto.InternalMessageInfo

func (m *MoveDataResponse) GetKvs() []*MoveDataResponse_Kv {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type MoveDataResponse_Kv struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDataResponse_Kv) Reset()         { *m = MoveDataResponse_Kv{} }
func (m *MoveDataResponse_Kv) String() string { return proto.CompactTextString(m) }
func (*MoveDataResponse_Kv) ProtoMessage()    {}
func (*MoveDataResponse_Kv) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{7, 0}
}

func (m *MoveDataResponse_Kv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDataResponse_Kv.Unmarshal(m, b)
}
func (m *MoveDataResponse_Kv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDataResponse_Kv.Marshal(b, m, deterministic)
}
func (m *MoveDataResponse_Kv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDataResponse_Kv.Merge(m, src)
}
func (m *MoveDataResponse_Kv) XXX_Size() int {
	return xxx_messageInfo_MoveDataResponse_Kv.Size(m)
}
func (m *MoveDataResponse_Kv) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDataResponse_Kv.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDataResponse_Kv proto.InternalMessageInfo

func (m *MoveDataResponse_Kv) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MoveDataResponse_Kv) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{8}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetAllResponse struct {
	Kvs                  []*GetAllResponse_Kvs `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{9}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetKvs() []*GetAllResponse_Kvs {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type GetAllResponse_Kvs struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse_Kvs) Reset()         { *m = GetAllResponse_Kvs{} }
func (m *GetAllResponse_Kvs) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse_Kvs) ProtoMessage()    {}
func (*GetAllResponse_Kvs) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{9, 0}
}

func (m *GetAllResponse_Kvs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse_Kvs.Unmarshal(m, b)
}
func (m *GetAllResponse_Kvs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse_Kvs.Marshal(b, m, deterministic)
}
func (m *GetAllResponse_Kvs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse_Kvs.Merge(m, src)
}
func (m *GetAllResponse_Kvs) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse_Kvs.Size(m)
}
func (m *GetAllResponse_Kvs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse_Kvs.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse_Kvs proto.InternalMessageInfo

func (m *GetAllResponse_Kvs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetAllResponse_Kvs) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*PutRequest)(nil), "PutRequest")
	proto.RegisterType((*PutResponse)(nil), "PutResponse")
	proto.RegisterType((*DelRequest)(nil), "DelRequest")
	proto.RegisterType((*DelResponse)(nil), "DelResponse")
	proto.RegisterType((*MoveDataRequest)(nil), "MoveDataRequest")
	proto.RegisterType((*MoveDataResponse)(nil), "MoveDataResponse")
	proto.RegisterType((*MoveDataResponse_Kv)(nil), "MoveDataResponse.Kv")
	proto.RegisterType((*GetAllRequest)(nil), "GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "GetAllResponse")
	proto.RegisterType((*GetAllResponse_Kvs)(nil), "GetAllResponse.Kvs")
}

func init() { proto.RegisterFile("slave.proto", fileDescriptor_5203a3ed916706d4) }

var fileDescriptor_5203a3ed916706d4 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x89, 0xfd, 0x9a, 0xd4, 0xb6, 0xae, 0x3d, 0xc4, 0x80, 0x12, 0x02, 0xda, 0x0a, 0xba,
	0x42, 0xeb, 0xcd, 0x93, 0x52, 0xe8, 0x21, 0x0a, 0x25, 0x47, 0x2f, 0x92, 0xda, 0x29, 0x42, 0x56,
	0xb7, 0x76, 0x37, 0x0b, 0xfe, 0x41, 0x7f, 0x97, 0xec, 0x36, 0x21, 0x69, 0xa5, 0xd0, 0x5b, 0x66,
	0xde, 0xce, 0x7b, 0x8f, 0x99, 0x17, 0x70, 0x05, 0x4b, 0x14, 0xd2, 0xd5, 0x9a, 0x4b, 0x1e, 0x5e,
	0x00, 0x4c, 0x51, 0xc6, 0xf8, 0x9d, 0xa1, 0x90, 0xa4, 0x07, 0x4e, 0x8a, 0x3f, 0x9e, 0x15, 0x58,
	0xc3, 0x56, 0xac, 0x3f, 0xc3, 0x31, 0xb8, 0x06, 0x17, 0x2b, 0xfe, 0x25, 0x90, 0x74, 0xc0, 0xe6,
	0xa9, 0xc1, 0x9b, 0xb1, 0xcd, 0x53, 0xd2, 0x87, 0x9a, 0x4a, 0x58, 0x86, 0x9e, 0x6d, 0x46, 0x36,
	0x45, 0x78, 0x0f, 0x30, 0xcb, 0xf6, 0x93, 0xee, 0x99, 0x1a, 0x80, 0x6b, 0xa6, 0x72, 0x29, 0x0f,
	0x1a, 0xef, 0x6b, 0x4c, 0x24, 0x2e, 0x72, 0xbd, 0xa2, 0xd4, 0x9e, 0x27, 0xc8, 0xf6, 0x7b, 0x1e,
	0x80, 0x6b, 0xf0, 0x92, 0x68, 0x81, 0x0c, 0x2b, 0x44, 0x79, 0x19, 0x46, 0xd0, 0x7d, 0xe1, 0x0a,
	0x27, 0x89, 0x4c, 0x0a, 0xb6, 0x73, 0x80, 0xe5, 0x9a, 0x7f, 0xbe, 0xb1, 0x64, 0x8e, 0xcc, 0xbc,
	0xaf, 0xc5, 0x2d, 0xdd, 0x79, 0xd6, 0x0d, 0x72, 0x06, 0x4d, 0xc9, 0x73, 0xd0, 0x36, 0x60, 0x43,
	0x72, 0x03, 0x85, 0x1f, 0xd0, 0x2b, 0xc9, 0x72, 0xe9, 0x2b, 0x70, 0x52, 0x25, 0x3c, 0x2b, 0x70,
	0x86, 0xee, 0xa8, 0x4f, 0x77, 0x71, 0x1a, 0xa9, 0x58, 0x3f, 0xf0, 0x6f, 0xc0, 0x8e, 0xd4, 0xc1,
	0x8b, 0xea, 0xc2, 0xf1, 0x14, 0xe5, 0x23, 0x2b, 0x56, 0x10, 0x2e, 0xa1, 0x53, 0x34, 0x72, 0xe1,
	0xcb, 0xaa, 0xf0, 0x29, 0xdd, 0x46, 0x69, 0xa4, 0xc4, 0x46, 0xf7, 0x16, 0x9c, 0x48, 0x89, 0x43,
	0x85, 0x47, 0xbf, 0x96, 0xf1, 0x19, 0x80, 0x33, 0x45, 0x49, 0x5c, 0x5a, 0x26, 0xc7, 0x6f, 0xd3,
	0x6a, 0x4c, 0xae, 0xa1, 0xbe, 0x91, 0x24, 0x1d, 0xba, 0x65, 0xd5, 0xef, 0xee, 0x78, 0xd1, 0x64,
	0xb3, 0x4c, 0x93, 0x95, 0x89, 0xf1, 0xdb, 0xb4, 0x1a, 0x84, 0x00, 0x9c, 0x09, 0x32, 0xe2, 0xd2,
	0xf2, 0xe8, 0x7e, 0x9b, 0x56, 0x2f, 0x7c, 0x07, 0xcd, 0x62, 0xb5, 0xa4, 0x47, 0x77, 0x4e, 0xea,
	0x9f, 0xfc, 0xdb, 0xfb, 0x53, 0xfd, 0xf5, 0x88, 0x3e, 0xac, 0xe6, 0xf3, 0xba, 0xf9, 0x09, 0xc6,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09, 0x46, 0xb1, 0x49, 0x13, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvClient is the client API for Kv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	MoveData(ctx context.Context, in *MoveDataRequest, opts ...grpc.CallOption) (*MoveDataResponse, error)
}

type kvClient struct {
	cc *grpc.ClientConn
}

func NewKvClient(cc *grpc.ClientConn) KvClient {
	return &kvClient{cc}
}

func (c *kvClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Kv/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/Kv/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/Kv/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, "/Kv/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) MoveData(ctx context.Context, in *MoveDataRequest, opts ...grpc.CallOption) (*MoveDataResponse, error) {
	out := new(MoveDataResponse)
	err := c.cc.Invoke(ctx, "/Kv/MoveData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvServer is the server API for Kv service.
type KvServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Del(context.Context, *DelRequest) (*DelResponse, error)
	MoveData(context.Context, *MoveDataRequest) (*MoveDataResponse, error)
}

func RegisterKvServer(s *grpc.Server, srv KvServer) {
	s.RegisterService(&_Kv_serviceDesc, srv)
}

func _Kv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kv/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kv/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kv/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_MoveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).MoveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kv/MoveData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).MoveData(ctx, req.(*MoveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Kv",
	HandlerType: (*KvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Kv_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Kv_GetAll_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Kv_Put_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Kv_Del_Handler,
		},
		{
			MethodName: "MoveData",
			Handler:    _Kv_MoveData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slave.proto",
}
